import { hashSync } from 'bcrypt-ts-edge'

const sampleData = {
  users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: hashSync('123456', 10),
      role: 'admin',
    },
    {
      name: 'Jane',
      email: 'jane@example.com',
      password: hashSync('123456', 10),
      role: 'user',
    },
  ],
  categories: [
    {
      name: 'Gạch Ốp Lát',
      slug: 'gach-op-lat',
    },
    {
      name: 'Thiết Bị Vệ Sinh',
      slug: 'thiet-bi-ve-sinh',
    },
    {
      name: 'Thiết Bị Bếp',
      slug: 'thiet-bi-bep',
    },
    {
      name: 'Phụ Kiện',
      slug: 'phu-kien',
    },
  ],
  brands: [
    {
      name: 'Viglacera',
      slug: 'viglacera',
    },
    {
      name: 'Toto',
      slug: 'toto',
    },
    {
      name: 'American Standard',
      slug: 'american-standard',
    },
    {
      name: 'Inax',
      slug: 'inax',
    },
    {
      name: 'Cotto',
      slug: 'cotto',
    },
  ],
  products: [
    {
      name: 'Gạch Granite Viglacera 60x60',
      slug: 'gach-granite-viglacera-60x60',
      sku: 'VIG-GR-6060-001',
      images: ['/assets/images/p1-1.jpeg', '/assets/images/p1-2.jpeg'],
      price: '299000',
      basePrice: '329000',
      discountPrice: '284000',
      stock: 500,
      description:
        'Gạch granite cao cấp Viglacera kích thước 60x60cm, bề mặt polished bóng gương, chống trơn trượt tốt.',
      isFeatured: true,
      banner: '/assets/images/banner-1.jpeg',
      attributes: {
        color: ['Gray', 'Dark Gray', 'Natural Stone'],
        size: ['60x60cm', '80x80cm'],
        material: ['Granite'],
        surface: ['Polished', 'High Gloss'],
        texture: ['Stone', 'Multicolor'],
        applicable_zone: ['Living Room Floor', 'Kitchen Floor', 'Commercial Space'],
        thickness: '9mm',
        tile_type: 'Floor Tile',
        slip_resistance: 'R10',
        origin: 'Vietnam',
        warranty: '2 years',
      },
    },
    {
      name: 'Bồn Cầu Toto CS769DW5',
      slug: 'bon-cau-toto-cs769dw5',
      sku: 'TOTO-BC-CS769DW5',
      images: ['/assets/images/p2-1.jpeg', '/assets/images/p2-2.jpeg'],
      price: '4500000',
      basePrice: '5000000',
      discountPrice: '4275000',
      stock: 50,
      description:
        'Bồn cầu một khối Toto CS769DW5, công nghệ xả Tornado Flush tiết kiệm nước, men sứ CeFiONtect chống bám bẩn.',
      isFeatured: true,
      banner: '/assets/images/banner-2.jpeg',
      attributes: {
        toiletries_type: 'Toilet',
        color: ['White'],
        material: ['Vitreous China'],
        design: {
          toilet: ['One-Piece', 'Floor-Mounted', 'Rimless', 'Soft Close'],
        },
        installation_type: 'Floor-Mounted',
        flush_type: 'Tornado Flush',
        water_consumption: '4.5L',
        origin: 'Vietnam',
        warranty: '2 years',
      },
    },
    {
      name: 'Chậu Rửa Bát Inax IF-6800SV',
      slug: 'chau-rua-bat-inax-if6800sv',
      sku: 'INAX-CRB-IF6800SV',
      images: ['/assets/images/p3-1.jpeg', '/assets/images/p3-2.jpeg'],
      price: '1850000',
      basePrice: '2100000',
      discountPrice: '1757500',
      stock: 30,
      description:
        'Chậu rửa bát Inax IF-6800SV inox 304, thiết kế 2 hộc, kích thước 800x450mm, chống xước và ăn mòn tốt.',
      attributes: {
        color: ['Silver', 'Chrome'],
        size: ['800x450mm', '1000x500mm'],
        material: ['Stainless Steel 304'],
        bowls: '2',
        installation_type: 'Undermount',
        origin: 'Vietnam',
        warranty: '3 years',
      },
    },
    {
      name: 'Vòi Lavabo American Standard CF-3701',
      slug: 'voi-lavabo-american-standard-cf3701',
      sku: 'AMST-VL-CF3701',
      images: ['/assets/images/p4-1.jpeg', '/assets/images/p4-2.jpeg'],
      price: '2100000',
      basePrice: '2300000',
      discountPrice: '1995000',
      stock: 100,
      description:
        'Vòi lavabo American Standard CF-3701, thiết kế hiện đại, mạ chrome sang trọng, van ceramic bền bỉ.',
      attributes: {
        toiletries_type: 'Faucet',
        color: ['Chrome', 'Silver'],
        material: ['Brass', 'Zinc Alloy'],
        design: {
          faucet: ['Single Handle', 'Deck-Mounted', 'High Arc', 'Swivel Spout'],
        },
        installation_type: 'Deck-Mounted',
        valve_type: 'Ceramic',
        origin: 'USA',
        warranty: '5 years',
      },
    },
    {
      name: 'Gạch Ốp Tường Cotto 30x60',
      slug: 'gach-op-tuong-cotto-30x60',
      sku: 'COTTO-GOT-3060-001',
      images: ['/assets/images/p1-1.jpeg', '/assets/images/p1-2.jpeg'],
      price: '180000',
      basePrice: '200000',
      discountPrice: '171000',
      stock: 800,
      description:
        'Gạch ốp tường Cotto 30x60cm, bề mặt mờ, vân đá tự nhiên, phù hợp cho phòng tắm và bếp.',
      attributes: {
        color: ['Beige', 'Cream', 'Brown'],
        size: ['30x60cm', '30x30cm'],
        material: ['Ceramic'],
        surface: ['Matte', 'Semi-Matte'],
        texture: ['Stone', 'Travertine'],
        applicable_zone: ['Bathroom Wall', 'Kitchen Wall', 'Wall'],
        thickness: '8mm',
        tile_type: 'Wall Tile',
        water_absorption: '3-6%',
        origin: 'Thailand',
        warranty: '1 year',
      },
    },
    {
      name: 'Sen Tắm Toto TX492SV',
      slug: 'sen-tam-toto-tx492sv',
      sku: 'TOTO-ST-TX492SV',
      images: ['/assets/images/p2-1.jpeg', '/assets/images/p2-2.jpeg'],
      price: '3200000',
      basePrice: '3500000',
      discountPrice: '3040000',
      stock: 45,
      description:
        'Sen tắm cây Toto TX492SV, vòi nhiệt độ, sen overhead 200mm, chất liệu đồng mạ chrome cao cấp.',
      attributes: {
        toiletries_type: 'Shower System',
        color: ['Chrome', 'Silver'],
        material: ['Brass', 'Stainless Steel 304'],
        design: {
          showerHead: ['Dual', 'Rain Shower', 'Handheld', 'Wall-Mounted', 'Multi-Function'],
        },
        installation_type: 'Wall-Mounted',
        valve_type: 'Thermostatic',
        origin: 'Vietnam',
        warranty: '3 years',
      },
    },
    {
      name: 'Bếp Từ Âm Inax IH-B330',
      slug: 'bep-tu-am-inax-ihb330',
      sku: 'INAX-BT-IHB330',
      images: ['/assets/images/p3-1.jpeg', '/assets/images/p3-2.jpeg'],
      price: '5500000',
      basePrice: '6000000',
      discountPrice: '5225000',
      stock: 25,
      description:
        'Bếp từ âm Inax IH-B330, 2 vùng nấu, công suất 3000W, mặt kính cường lực, điều khiển cảm ứng.',
      attributes: {
        color: ['Black'],
        size: ['590x520mm'],
        material: ['Glass', 'Ceramic'],
        zones: '2',
        power: '3000W',
        control: 'Touch Screen',
        installation_type: 'Built-in',
        safety: ['Auto Shutoff', 'Child Lock', 'Overheating Protection', 'Residual Heat Indicator'],
        origin: 'Vietnam',
        warranty: '2 years',
      },
    },
    {
      name: 'Phụ Kiện Phòng Tắm American Standard',
      slug: 'phu-kien-phong-tam-american-standard',
      sku: 'AMST-PK-SET001',
      images: ['/assets/images/p4-1.jpeg', '/assets/images/p4-2.jpeg'],
      price: '1200000',
      stock: 150,
      description:
        'Bộ phụ kiện phòng tắm American Standard gồm móc áo, thanh vắt khăn, giá để giấy, mạ chrome sáng bóng.',
      attributes: {
        toiletries_type: 'Accessory',
        color: ['Chrome', 'Silver'],
        material: ['Brass', 'Stainless Steel 304'],
        design: {
          accessory: ['Towel Bar', 'Robe Hook', 'Paper Holder', 'Towel Ring'],
        },
        installation_type: 'Wall-Mounted',
        items: '4 pieces',
        includes: ['Towel Bar', 'Robe Hook', 'Paper Holder', 'Towel Ring', 'Mounting hardware', 'Screws and anchors'],
        origin: 'USA',
        warranty: '2 years',
      },
    },
  ],
}

export default sampleData
